moved help to bottom, to display on any EC

diff --git a/mktar b/mktar
--- a/mktar
+++ b/mktar
@@ -31,20 +31,20 @@ if [ -e "$1" ]; then
             tar -cvf - "${_dir}" | xz -6e > "${_dir}".tar.${_ext};
             ;;
         *)
-            echo "${_base}: Could not create '${_dir}.tar.${_ext}'";
-            cat  <<INFO
-Usage: ${_base} [gz|bz2|xz] <files/directory>
-       ${_base} foobar.d     # -> foobar.d.tar.xz";
-       ${_base} gz foobar.d  # -> foobar.d.tar.gz\n";
-
-INFO
+            echo -e ":: ${_base}: Could not create '${_dir}.tar.${_ext}'\n";
             ERR=1;
             ;;
     esac
 else
-    echo "'${_dir}' is not a valid file/directory";
+    echo -e ":: '${_dir}' is not a valid file/directory\n";
     ERR=1;
 fi
 
-exit ${ERR};
+[[ ${ERR} != 0 ]] && cat  <<INFO
+Usage: ${_base} [gz|bz2|xz] <files/directory>
+       ${_base} foobar.d     # -> foobar.d.tar.xz
+       ${_base} gz foobar.d  # -> foobar.d.tar.gz
 
+INFO
+
+exit ${ERR};
